#!/usr/bin/env bash
cd "$(dirname "$0")" || exit;

export "$(grep -v "^#" "${ENV_FILE:=.env}" | xargs)"

pg_dump -U postgres "$DB_NAME" | \
	restic backup --tag "database" --stdin --stdin-filename="${DB_NAME}.sql"
